# beta = 0.1
accelerate launch --config_file /home/qiuwenqi/LLM/Fedfinetune/FCL/PILoRA-revise/PILoRA-cifar/configs/default_config.yaml /home/qiuwenqi/LLM/Fedfinetune/FCL/PILoRA-revise/PILoRA-cifar/federated_main.py --mode federated --is_peft=1 --model=bart_classification_bart-base --baseline bart_classification_bart-base_vanlina --dataset=fewrel --iid=0 --encoders_lr=1e-3 --epochs=3 --gpu 0 --task_num 7 --fg_nc 10 --total_classes 80 --local_ep 5 --num_users 20 --client_local 5 --niid_type D --beta 0.1 --local_bs=64 --r=32 --lamb=1
accelerate launch --config_file /home/qiuwenqi/LLM/Fedfinetune/FCL/PILoRA-revise/PILoRA-cifar/configs/default_config.yaml /home/qiuwenqi/LLM/Fedfinetune/FCL/PILoRA-revise/PILoRA-cifar/federated_main.py --mode federated --is_peft=0 --model=bart_classification_bart-base --baseline bart_classification_bart-base_vanlina --dataset=fewrel --iid=0 --encoders_lr=1e-5 --epochs=3 --gpu 0 --task_num 7 --fg_nc 10 --total_classes 80 --local_ep 5 --num_users 20 --client_local 5 --niid_type D --beta 0.1 --local_bs=64 --r=32 --lamb=1
sleep 5
accelerate launch --config_file /home/qiuwenqi/LLM/Fedfinetune/FCL/PILoRA-revise/PILoRA-cifar/configs/default_config.yaml /home/qiuwenqi/LLM/Fedfinetune/FCL/PILoRA-revise/PILoRA-cifar/federated_main.py --mode federated --is_peft=1 --model=bart_classification_bart-base --baseline bart_classification_bart-base_vanlina --dataset=fewrel --iid=0 --encoders_lr=1e-3 --epochs=3 --gpu 0 --task_num 7 --fg_nc 10 --total_classes 80 --local_ep 5 --num_users 20 --client_local 5 --niid_type D --beta 1 --local_bs=64 --r=32 --lamb=1
sleep 5
accelerate launch --config_file /home/qiuwenqi/LLM/Fedfinetune/FCL/PILoRA-revise/PILoRA-cifar/configs/default_config.yaml /home/qiuwenqi/LLM/Fedfinetune/FCL/PILoRA-revise/PILoRA-cifar/federated_main.py --mode federated --is_peft=1 --model=bart_classification_bart-base --baseline bart_classification_bart-base_vanlina --dataset=fewrel --iid=0 --encoders_lr=1e-3 --epochs=3 --gpu 0 --task_num 7 --fg_nc 10 --total_classes 80 --local_ep 5 --num_users 20 --client_local 5 --niid_type D --beta 10 --local_bs=64 --r=32 --lamb=1
sleep 5
# FL_full
accelerate launch --config_file /home/qiuwenqi/LLM/Fedfinetune/FCL/PILoRA-revise/PILoRA-cifar/configs/default_config.yaml /home/qiuwenqi/LLM/Fedfinetune/FCL/PILoRA-revise/PILoRA-cifar/federated_main.py --mode federated --is_peft=0 --model=bart_classification_bart-base --baseline bart_classification_bart-base_vanlina --dataset=fewrel --iid=0 --encoders_lr=1e-5 --epochs=3 --gpu 0 --task_num 7 --fg_nc 10 --total_classes 80 --local_ep 5 --num_users 20 --client_local 5 --niid_type D --beta 1 --local_bs=64 --r=32 --lamb=1
sleep 5
accelerate launch --config_file /home/qiuwenqi/LLM/Fedfinetune/FCL/PILoRA-revise/PILoRA-cifar/configs/default_config.yaml /home/qiuwenqi/LLM/Fedfinetune/FCL/PILoRA-revise/PILoRA-cifar/federated_main.py --mode federated --is_peft=1 --model=bart_classification_bart-base --baseline bart_classification_bart-base_ewc --dataset=fewrel --iid=0 --encoders_lr=1e-3 --epochs=3 --gpu 0 --task_num 7 --fg_nc 10 --total_classes 80 --local_ep 3 --num_users 20 --client_local 5 --niid_type D --beta 0.1 --local_bs=1 --r=16 --lamb=1
sleep 5

